// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::drivefrontRightMotor = NULL;
SpeedController* RobotMap::drivefrontLeftMotor = NULL;
SpeedController* RobotMap::drivebackRightMotor = NULL;
SpeedController* RobotMap::drivebackLeftMotor = NULL;
RobotDrive* RobotMap::drivemecDrive = NULL;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	drivefrontRightMotor = new Talon(2);
	lw->AddActuator("Drive", "frontRightMotor", (Talon*) drivefrontRightMotor);
	
	drivefrontLeftMotor = new Talon(1);
	lw->AddActuator("Drive", "frontLeftMotor", (Talon*) drivefrontLeftMotor);
	
	drivebackRightMotor = new Talon(3);
	lw->AddActuator("Drive", "backRightMotor", (Talon*) drivebackRightMotor);
	
	drivebackLeftMotor = new Talon(4);
	lw->AddActuator("Drive", "backLeftMotor", (Talon*) drivebackLeftMotor);
	
	drivemecDrive = new RobotDrive(drivefrontLeftMotor, drivebackLeftMotor,
              drivefrontRightMotor, drivebackRightMotor);
	
	drivemecDrive->SetSafetyEnabled(true);
        drivemecDrive->SetExpiration(0.1);
        drivemecDrive->SetSensitivity(0.5);
        drivemecDrive->SetMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
